require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'iDocus' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'react-native-image-editor', :path => '../node_modules/@react-native-community/image-editor'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'react-native-exif', :path => '../node_modules/react-native-exif'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  pod 'RealmJS', :path => '../node_modules/realm'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  target 'iDocusTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'iDocus-tvOS' do
  # Pods for iDocus-tvOS

  target 'iDocus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
