# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'iDocus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iDocus
  pod 'Firebase/Messaging', '4.0.0'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'iDocus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing



    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

    pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  end

  target 'iDocusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iDocus-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iDocus-tvOS

  #target 'iDocus-tvOSTests' do
#inherit! :search_paths
    # Pods for testing
#end

end
